### PR TITLE
Added agglomerative clustering on graphs.

### PR DESCRIPTION
**Pull request by schwobr**
Started to implement graph clustering methods. The goal of this PR is to push a minimally functional graph API, including:
* Graph and tree structures (using [treez](https://github.com/ArnaudAbreu/treez) from @ArnaudAbreu / [networkx](https://networkx.org/documentation/stable/index.html)) [Ongoing]
* Graph clustering algorithms [Ongoing]
* Cell graph construction using PathAIA and [HoVer-Net](https://github.com/vqdang/hover_net) [TODO]

20/07/2021: For now I simply implemented and documented an agglomerative clustering method I used. It needs a lot of polishing in order to be more flexible and reusable. It is still a good discussion baseline for future design choices when it comes to graphs.

22/07/2021: Started including graph and tree structures taking inspiration from [treez](https://github.com/ArnaudAbreu/treez). Modified `AgglomerativeClustering` so that it is compatible with these structures.

### CODE REVIEW

**Comment by ArnaudAbreu** [comment]
Nice PR, I really enjoy your `sortedDict` version of agglomeration! (Probably the only way to get _average-linkage_ working efficiently^^).
Amazing work!

**Review by pilarOrtega — APPROVED** [review]

**Comment by pilarOrtega** [comment]
thanks Robin! great initiative :)

**Review by ArnaudAbreu — APPROVED** [review]

**Comment by schwobr** [comment]
@ArnaudAbreu I added the base structure for graphs and trees and made my algorithm compatible. There is still some refactoring to do (mainly moving Kruskal into the `clustering` module and adding methods for editing trees) and I did not yet test anything but it should be a good baseline.

**Comment by ArnaudAbreu** [comment]
I had a look at it and it looks perfect!
I think we should merge before we go further, just to keep this PR simple.
You now have administrator's privileges on the repo, so I let you do it when you're ok with the changes. I think we don't need to wait for Laurent's review since he's on holiday.

**Pull request merged**
